# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cmake"  # Assuming CMake for VTK and ITK
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "VTK"
      - dependency-name: "ITK"

  - package-ecosystem: "any"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "DCMTK"

  - package-ecosystem: "qt"  # Assuming Qt for Qt library
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Qt"
